apiVersion: v1
kind: Service
metadata:
  name: cache-server
spec:
  selector:
    app: cache-server
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: redis
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: metrics
  type: ClusterIP
